In [2]:
## How probable is it for மழை to become மலை?

x = "மழை"
y = "மலை"

In [3]:
from com_1_edit_distance import com_1_edit_distance
com_1_edit_distance(x, y)

(1, 'substitution', 1, None)

In [4]:
for i, j in zip(x, y):
    print(i ,j)

ம ம
ழ ல
ை ை


In [5]:
import numpy as np
count_array = np.load("./src/count_array.npy")

In [6]:
count_array

array([7.30000e+01, 8.76900e+03, 2.89300e+03, 4.07800e+03, 3.57000e+02,
       2.90600e+03, 4.95000e+02, 1.24000e+03, 6.40000e+02, 2.19000e+02,
       8.36000e+02, 3.78000e+02, 2.90000e+01, 5.95530e+04, 4.87200e+03,
       3.16400e+04, 5.30000e+02, 2.59500e+03, 3.18410e+04, 1.25940e+04,
       5.93230e+04, 1.31110e+04, 2.19290e+04, 4.25730e+04, 4.83590e+04,
       1.63850e+04, 3.68850e+04, 1.41140e+04, 3.16730e+04, 1.04860e+04,
       6.05600e+03, 2.66390e+04, 0.00000e+00, 9.00000e+02, 8.61000e+02,
       1.99000e+02, 3.52420e+04, 5.77020e+04, 4.66800e+03, 5.37230e+04,
       5.62000e+03, 6.89300e+03, 5.95300e+03, 2.11220e+04, 5.55200e+03,
       6.77000e+03, 3.84000e+02, 1.39191e+05])

In [7]:
sub = np.load("./src/sub.npy")
sub

array([[1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [1.000e+00, 1.000e+00, 4.120e+03, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [1.000e+00, 1.462e+03, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       ...,
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 9.160e+02,
        1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 6.600e+01, 1.000e+00,
        1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [8]:
sub.shape

(48, 48)

In [9]:
all_letters_unicode_b10 = np.array([2947,2949,2950,2951,2952,2953,2954,2958,2959,2960,2962,2963,2964,2965,2969,2970,2972,2974,2975,2979,2980,2984,2985,2986,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999,3000,3001,3006,3007,3008,3009,3010,3014,3015,3016,3018,3019,3020,3021])

In [10]:
all_letters_unicode_b10.shape

(48,)

In [11]:
err = com_1_edit_distance(x, y)
err

(1, 'substitution', 1, None)

In [12]:
pre = np.where(all_letters_unicode_b10 == ord(x[err[2]]))[0][0]
post = np.where(all_letters_unicode_b10 == ord(y[err[2]]))[0][0]

In [13]:
pre, post

(30, 28)

In [14]:
sub[30, 28]

1354.0

In [15]:
count_array

array([7.30000e+01, 8.76900e+03, 2.89300e+03, 4.07800e+03, 3.57000e+02,
       2.90600e+03, 4.95000e+02, 1.24000e+03, 6.40000e+02, 2.19000e+02,
       8.36000e+02, 3.78000e+02, 2.90000e+01, 5.95530e+04, 4.87200e+03,
       3.16400e+04, 5.30000e+02, 2.59500e+03, 3.18410e+04, 1.25940e+04,
       5.93230e+04, 1.31110e+04, 2.19290e+04, 4.25730e+04, 4.83590e+04,
       1.63850e+04, 3.68850e+04, 1.41140e+04, 3.16730e+04, 1.04860e+04,
       6.05600e+03, 2.66390e+04, 0.00000e+00, 9.00000e+02, 8.61000e+02,
       1.99000e+02, 3.52420e+04, 5.77020e+04, 4.66800e+03, 5.37230e+04,
       5.62000e+03, 6.89300e+03, 5.95300e+03, 2.11220e+04, 5.55200e+03,
       6.77000e+03, 3.84000e+02, 1.39191e+05])

In [16]:
len(count_array)

48

In [17]:
count_array[28]

31673.0

In [18]:
## Substitution
sub[30, 28] / count_array[28]

0.04274934486786853

In [19]:
x = "அர்த்தம்"
y = "அத்ர்தம்"

tra = np.load("./src/tra.npy")
tra

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 2., 1.],
       [1., 1., 1., ..., 3., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [20]:
import pickle

with open("./src/_count.pkl", "rb") as file:
    _count = pickle.load(file)
_count

{(0, 0): 3,
 (0, 1): 1,
 (0, 2): 1,
 (0, 3): 1,
 (0, 4): 1,
 (0, 5): 1,
 (0, 6): 1,
 (0, 7): 1,
 (0, 8): 1,
 (0, 9): 2,
 (0, 10): 1,
 (0, 11): 1,
 (0, 12): 2,
 (0, 13): 44,
 (0, 14): 1,
 (0, 15): 6,
 (0, 16): 1,
 (0, 17): 1,
 (0, 18): 8,
 (0, 19): 4,
 (0, 20): 27,
 (0, 21): 2,
 (0, 22): 15,
 (0, 23): 14,
 (0, 24): 14,
 (0, 25): 11,
 (0, 26): 7,
 (0, 27): 15,
 (0, 28): 23,
 (0, 29): 3,
 (0, 30): 1,
 (0, 31): 5,
 (0, 32): 1,
 (0, 33): 1,
 (0, 34): 1,
 (0, 35): 1,
 (0, 36): 15,
 (0, 37): 24,
 (0, 38): 1,
 (0, 39): 33,
 (0, 40): 1,
 (0, 41): 9,
 (0, 42): 4,
 (0, 43): 12,
 (0, 44): 4,
 (0, 45): 4,
 (0, 46): 1,
 (0, 47): 46,
 (1, 0): 29,
 (1, 1): 5,
 (1, 2): 5,
 (1, 3): 6,
 (1, 4): 1,
 (1, 5): 5,
 (1, 6): 1,
 (1, 7): 3,
 (1, 8): 1,
 (1, 9): 2,
 (1, 10): 3,
 (1, 11): 1,
 (1, 12): 2,
 (1, 13): 5422,
 (1, 14): 618,
 (1, 15): 2885,
 (1, 16): 35,
 (1, 17): 275,
 (1, 18): 2519,
 (1, 19): 1124,
 (1, 20): 5890,
 (1, 21): 1120,
 (1, 22): 2784,
 (1, 23): 3295,
 (1, 24): 4808,
 (1, 25): 1639,
 (1, 26):

In [21]:
err = com_1_edit_distance(x, y)

In [22]:
i = np.where(all_letters_unicode_b10 == ord(x[err[2]]))[0][0]
j = np.where(all_letters_unicode_b10 == ord(x[err[3]]))[0][0]
print(i, j)

26 20


In [23]:
tra[26, 20]

1612.0

In [24]:
(26, 20) in _count

True

In [25]:
_count[(26, 20)]

14431

In [26]:
tra[26, 20] / _count[(26, 20)]

0.11170397061880674

In [27]:
## Deletion
with open("./src/del.npy", "rb") as file:
    _del = np.load(file)
_del

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [17.,  1.,  1., ...,  1.,  1.,  1.],
       [ 2.,  1.,  1., ...,  1.,  1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  3.,  5., ...,  1.,  1.,  1.]])

In [28]:
x = "சாதிசம்"
y = "சாதசம்"

err = com_1_edit_distance(x, y)

In [29]:
err

(1, 'deletion', 3, None)

In [30]:
i = np.where(all_letters_unicode_b10 == ord(x[err[2]-1]))[0][0]
j = np.where(all_letters_unicode_b10 == ord(x[err[2]]))[0][0]
print(i, j)

20 37


In [31]:
_del[20, 37]

3408.0

In [32]:
_count[(20, 37)]

25950

In [33]:
_del[20, 37] / _count[(20, 37)]

0.13132947976878612

In [34]:
## Insertion
with open("./src/ins.npy", "rb") as file:
    ins = np.load(file)
ins

array([[  1.,   1.,   1., ...,   1.,   1.,   1.],
       [  1.,   1.,   1., ...,   1.,   1.,   1.],
       [  1.,   1.,   1., ...,   1.,   1.,   1.],
       ...,
       [  1., 168., 191., ...,   1.,   1.,   1.],
       [  1.,  17.,  13., ...,   1.,   1.,   1.],
       [  1.,   1.,   1., ...,   1.,   1.,   1.]])

In [35]:
x = "அகக்கர்ணம்"
y = "அகக்கரப்ணம்"

err = com_1_edit_distance(x, y)

In [36]:
err

(1, 'insertion', 6, None)

In [37]:
ins.shape

(48, 48)

In [38]:
i = np.where(all_letters_unicode_b10 == ord(y[err[2]-1]))[0][0]
j = np.where(all_letters_unicode_b10 == ord(y[err[2]]))[0][0]

In [39]:
i, j

(26, 23)

In [40]:
ins[i, j]

1101.0

In [41]:
count_array[i]

36885.0

In [42]:
ins[i, j] / count_array[i]

0.029849532330215534

In [ ]:
def compute_channel_probability(x, y, err):
    if err[1] == "insertion":
        i = np.where(all_letters_unicode_b10 == ord(y[err[2]-1]))[0][0]
        j = np.where(all_letters_unicode_b10 == ord(y[err[2]]))[0][0]
        
        return ins[i, j] / count_array[i]

    elif err[1] == "transposition":
        i = np.where(all_letters_unicode_b10 == ord(x[err[2]]))[0][0]
        j = np.where(all_letters_unicode_b10 == ord(x[err[3]]))[0][0]
        
        return tra[i, j] / _count[(i, j)]
    
    elif err[1] == "substitution":
        pre = np.where(all_letters_unicode_b10 == ord(x[err[2]]))[0][0]
        post = np.where(all_letters_unicode_b10 == ord(y[err[2]]))[0][0]

        return sub[pre, post] / count_array[post]
        
    
    elif err[1] == "deletion":
        i = np.where(all_letters_unicode_b10 == ord(x[err[2]-1]))[0][0]
        j = np.where(all_letters_unicode_b10 == ord(x[err[2]]))[0][0]
        
        return _del[i, j] / _count[(i, j)]
    
    else:
        raise Exception("Unkown Error Cause")